# gen_arecibo.py - rewrite the Arecibo message's population field with today's
# world population, then emit a C++ header of the packed bits for bitforge.
import sys

ORIG_POP = 4292853750          # 1974 value encoded in the real message
NEW_POP  = 8303169803          # world population, 2026-07-18 (Worldometer live)

root = r'C:\Brainstorm\bitforge'
with open(root + r'\arecibo\arecibo_1974.txt') as f:
    grid = [ln.strip() for ln in f if ln.strip()]

assert len(grid) == 73, f'rows={len(grid)}'
for i, row in enumerate(grid):
    assert len(row) == 23, f'row {i} len={len(row)}'
R, C = 73, 23

def get_block(r, c, h, w):
    return [[int(grid[r+i][c+j]) for j in range(w)] for i in range(h)]

def seq_from_block(blk, rowrev, colrev):
    rows = blk[::-1] if rowrev else [r[:] for r in blk]
    seq = []
    for row in rows:
        seq.extend(row[::-1] if colrev else row)
    return seq

def to_int(seq, msbfirst):
    s = seq if msbfirst else seq[::-1]
    v = 0
    for b in s:
        v = (v << 1) | b
    return v

# Locate the 6x6 population block + its orientation by matching the known value.
matches = []
for r in range(R-6+1):
    for c in range(C-6+1):
        blk = get_block(r, c, 6, 6)
        for rowrev in (0, 1):
            for colrev in (0, 1):
                for msb in (0, 1):
                    if to_int(seq_from_block(blk, rowrev, colrev), msb) == ORIG_POP:
                        matches.append((r, c, rowrev, colrev, msb))
print('matches:', matches)
if not matches:
    print('POPULATION BLOCK NOT FOUND - grid transcription is wrong'); sys.exit(1)
plausible = [m for m in matches if 40 <= m[0] <= 60 and 12 <= m[1] <= 22] or matches
r, c, rowrev, colrev, msb = plausible[0]
print(f'population block: row={r} col={c} rowrev={rowrev} colrev={colrev} msbfirst={msb}')

def block_from_int(val, rowrev, colrev, msb):
    bits = [(val >> i) & 1 for i in range(36)][::-1]   # MSB-first, length 36
    seq = bits if msb else bits[::-1]
    rows = [seq[i*6:(i+1)*6] for i in range(6)]
    if colrev: rows = [row[::-1] for row in rows]
    if rowrev: rows = rows[::-1]
    return rows

newblk = block_from_int(NEW_POP, rowrev, colrev, msb)
assert to_int(seq_from_block(newblk, rowrev, colrev), msb) == NEW_POP, 'roundtrip fail'

g2 = [list(row) for row in grid]
for i in range(6):
    for j in range(6):
        g2[r+i][c+j] = str(newblk[i][j])
g2 = [''.join(row) for row in g2]

with open(root + r'\arecibo\arecibo_2026.txt', 'w') as f:
    f.write('\n'.join(g2) + '\n')

print(f'orig decode = {to_int(seq_from_block(get_block(r,c,6,6), rowrev, colrev), msb)} (want {ORIG_POP})')
print(f'NEW_POP     = {NEW_POP}  ({NEW_POP.bit_length()} bits)')
print(f'\n1974 population block rows {r}-{r+5}:')
for i in range(r, r+6): print('  ', grid[i], '  ->  ', g2[i])

def pack(g):
    bits = ''.join(g)
    assert len(bits) == R*C == 1679
    out = bytearray((len(bits)+7)//8)
    for i, ch in enumerate(bits):
        if ch == '1':
            out[i>>3] |= (1 << (7-(i & 7)))
    return out

new_bytes  = pack(g2)
orig_bytes = pack(grid)

def emit(name, data):
    lines = ['    ' + ', '.join(f'0x{b:02X}' for b in data[i:i+12]) + ','
             for i in range(0, len(data), 12)]
    return f'static const unsigned char {name}[{len(data)}] = {{\n' + '\n'.join(lines) + '\n};\n'

hdr = f'''// arecibo.h - GENERATED by arecibo/gen_arecibo.py (do not hand-edit)
// The 1974 Arecibo message with its population field rewritten to today's world
// population. 1679 bits (73 rows x 23 cols), row-major, MSB-first within each
// byte -- render at 23 columns to see the picture.
#pragma once
namespace bf {{
static const int AR_ROWS = {R};
static const int AR_COLS = {C};
static const int AR_BITS = {R*C};
static const unsigned long long AR_POP_1974 = {ORIG_POP}ULL;
static const unsigned long long AR_POP_NOW  = {NEW_POP}ULL;

{emit('AR_MSG', new_bytes)}
{emit('AR_MSG_1974', orig_bytes)}
}} // namespace bf
'''
with open(root + r'\core\arecibo.h', 'w') as f:
    f.write(hdr)
print('\nwrote core/arecibo.h  and  arecibo/arecibo_2026.txt')
